services:
  - type: web
    name: liszt
    runtime: node
    plan: free
    region: singapore
    buildCommand: npm ci
    startCommand: npm start
    healthCheckPath: /
    autoDeployTrigger: commit
