services:
  - type: web
    name: liszt
    runtime: node
    plan: free
    region: singapore
    buildCommand: yarn
    startCommand: yarn start
    healthCheckPath: /
    autoDeployTrigger: commit
